name: hope_button
description: This is a very simple and useful button widget, you can use this button for any purpose, have a good rest.
version: 0.0.1
homepage: https://github.com/Umidjon-18/hope_button

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0





flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
